config/routes.rb
Rails.application.routes.draw do

  resources :asset_fleets do
    collection do
      get 'orphaned_assets'

      get 'new_asset'
      get 'add_asset'
      get 'new_fleet'

      get 'builder'
      get 'runner'
    end

    member do
      delete 'remove_asset'
    end

  end

  # NTD Forms Controllers
  resources :forms, :only => [] do
    resources :ntd_forms do

      # Build controller for form wizard
      resources :steps, controller: 'ntd_forms/steps'

      collection do
        get   'download_file'
      end

      member do
        get 'fire_workflow_event'
        get 'generate'
      end

      resources :comments

    end
  end
  
end

app/models/asset_fleet_type.rb
class AssetFleetType < ActiveRecord::Base
  # All types that are available
  scope :active, -> { where(:active => true) }

  def to_s
    class_name
  end

  def group_by_fields
    standard_group_by_fields + custom_group_by_fields
  end

  def standard_group_by_fields
    groups.split(',')
  end

  def custom_group_by_fields
    custom_groups.split(',')
  end

  def label_fields
    label_groups.split(',')
  end
end

app/controllers/asset_fleets_controller.rb
class AssetFleetsController < OrganizationAwareController

  layout 'asset_fleets'

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Fleets", :asset_fleets_path

  before_action :set_asset_fleet, only: [:show, :edit, :update, :destroy, :remove_asset]

  before_action :set_form_vars, only: [:orphaned_assets, :builder]
  
  # GET /asset_fleets
  def index
    params[:sort] ||= 'ntd_id'

    @fta_asset_category = (FtaAssetCategory.find_by(id: params[:fta_asset_category_id]) || FtaAssetCategory.first)
    @asset_fleet_types = AssetFleetType.where(class_name: @fta_asset_category.asset_types.pluck(:class_name))
    # Go ahead and join with assets since almost every query requires it
    @asset_fleets = AssetFleet.where(organization_id: @organization_list, asset_fleet_type_id: @asset_fleet_types.pluck(:id)).distinct.joins(:assets)

    case @fta_asset_category.name
    when "Equipment"
      crumb = "Support Vehicles"
      @text_search_prompt = 'NTD ID/Agency Fleet ID/Fleet Name'
      include_fleet_name = true
      @vehicle_types = FtaSupportVehicleType.where(id: @asset_fleets.uniq.pluck(:fta_support_vehicle_type_id))
      use_support_vehicle_types = true
      # Disallow/map certain sort parameters
      case params[:sort]
      when 'primary_fta_service_type_id', 'active_count'
        params[:sort] = 'ntd_id'
      when 'fta_vehicle_type_id'
        params[:sort] = 'fta_support_vehicle_type_id'
      end
    else # Primarily Revenue vehicles for now
      crumb =  @fta_asset_category.to_s
      @text_search_prompt = 'NTD ID'
      include_fleet_name = false
      @service_types = FtaServiceType.active.all
      @vehicle_types = FtaVehicleType.where(id: @asset_fleets.uniq.pluck(:fta_vehicle_type_id))
      use_support_vehicle_types = false
      # Disallow/map certain sort parameters
      case params[:sort]
      when 'fleet_name'
        params[:sort] = 'ntd_id'
      when 'fta_support_vehicle_type_id'
        params[:sort] = 'fta_vehicle_type_id'
      end
    end
    
    case params[:sort]
    when 'organization'
      params[:sort] = 'organizations.short_name'
      @asset_fleets = @asset_fleets.joins(:organization)
    when 'ntd_id', 'agency_fleet_id', 'fleet_name'
      # Columns of asset_fleets, do nothing
    when 'primary_fta_mode_type_id'
      params[:sort] = 'assets_fta_mode_types.fta_mode_type_id'
      @asset_fleets = @asset_fleets
                      .joins("INNER JOIN assets_fta_mode_types ON assets.id = assets_fta_mode_types.asset_id")
                      .where(assets_fta_mode_types: {is_primary: true})

    when 'primary_fta_service_type_id'
      params[:sort] = 'assets_fta_service_types.fta_service_type_id'
      @asset_fleets = @asset_fleets
                      .joins("INNER JOIN assets_fta_service_types ON assets.id = assets_fta_service_types.asset_id")
                      .where(assets_fta_service_types: {is_primary: true})
    else
      # Asset field
      params[:sort] = "assets.#{params[:sort]}"
    end
    
    add_breadcrumb crumb

    # Set up filter collections
    @primary_modes = FtaModeType.where(id: AssetsFtaModeType.joins(:fta_mode_type)
                                        .where(assets_fta_mode_types: {is_primary: true}, asset_id: @asset_fleets.pluck('assets_asset_fleets.asset_id'))
                                       .uniq.pluck(:fta_mode_type_id))
    @manufacturers = Manufacturer.where(id: @asset_fleets.uniq.pluck(:manufacturer_id))
    
    # Filter results
    # Primary FTA Mode Type is particularly messy
    set_var_and_yield_if_present :primary_fta_mode_type_id do
      @asset_fleets = @asset_fleets
                      .joins("INNER JOIN assets_fta_mode_types ON assets.id = assets_fta_mode_types.asset_id")
                      .where(assets_fta_mode_types: {fta_mode_type_id: @primary_fta_mode_type_id,
                                                     is_primary: true})
    end

    # As is Primary FTA Service Type
    set_var_and_yield_if_present :primary_fta_service_type_id do
      @asset_fleets = @asset_fleets
                      .joins("INNER JOIN assets_fta_service_types ON assets.id = assets_fta_service_types.asset_id")
                      .where(assets_fta_service_types: {fta_service_type_id: @primary_fta_service_type_id,
                                                        is_primary: true})
    end

    # Drop into arel for OR of LIKE queries for text_search
    set_var_and_yield_if_present :search_text do
      ntd_id = Integer(@search_text, 10) rescue nil
      asset_fleet_table = AssetFleet.arel_table

      if ntd_id && include_fleet_name
        @asset_fleets = @asset_fleets.where(asset_fleet_table[:agency_fleet_id].matches("%#{@search_text}%")
                                             .or(asset_fleet_table[:fleet_name].matches("%#{@search_text}%"))
                                             .or(asset_fleet_table[:ntd_id].eq(ntd_id)))
      elsif ntd_id
        @asset_fleets = @asset_fleets.where(asset_fleet_table[:agency_fleet_id].matches("%#{@search_text}%")
                                             .or(asset_fleet_table[:ntd_id].eq(ntd_id)))

      elsif include_fleet_name
        @asset_fleets = @asset_fleets.where(asset_fleet_table[:agency_fleet_id].matches("%#{@search_text}%")
                                             .or(asset_fleet_table[:fleet_name].matches("%#{@search_text}%")))
      else
        @asset_fleets = @asset_fleets.where(asset_fleet_table[:agency_fleet_id].matches("%#{@search_text}%"))
      end
    end

    set_var_and_yield_if_present :fta_vehicle_type_id do
      if use_support_vehicle_types
        @asset_fleets = @asset_fleets.where(assets: {fta_support_vehicle_type_id: @fta_vehicle_type_id})
      else
        @asset_fleets = @asset_fleets.where(assets: {fta_vehicle_type_id: @fta_vehicle_type_id})
      end
    end
    
    set_var_and_yield_if_present :manufacturer_id do
      @asset_fleets = @asset_fleets.where(assets: {manufacturer_id: @manufacturer_id})
    end

    set_var_and_yield_if_present :manufacture_year do
      @asset_fleets = @asset_fleets.where(assets: {manufacture_year: @manufacture_year})
    end

    @status = params[:status] || 'Active'
    if @status == 'Active'
      @asset_fleets = @asset_fleets.where(assets: {disposition_date: nil, fta_emergency_contingency_fleet: false})
    else
      @asset_fleets = @asset_fleets
                      .where.not(id: @asset_fleets.where(assets: {disposition_date: nil, fta_emergency_contingency_fleet: false}).pluck(:id))
    end
    
    respond_to do |format|
      format.html 
      format.json {
        render :json => {
            :total => @asset_fleets.count,
            :rows =>  @asset_fleets.order("#{params[:sort]} #{params[:order]}").limit(params[:limit]).offset(params[:offset])
        }
      }
      format.xls
    end
  end

  def orphaned_assets
    # check that an order param was provided otherwise use asset_tag as the default
    params[:sort] ||= 'asset_tag'

    [:asset_type_id, :manufacturer_id, :manufacturer_model, :manufacture_year,
     :asset_subtype_id, :vehicle_type, :service_status_type_id].each do |p|
      set_var_and_yield_if_present p do
        @orphaned_assets = @orphaned_assets.where(p => params[p])
      end
    end

    set_var_and_yield_if_present :search_text do
      asset_table = Asset.arel_table

      @orphaned_assets = @orphaned_assets
                         .where(asset_table[:asset_tag].matches("%#{@search_text}%")
                                 .or(asset_table[:external_id].matches("%#{@search_text}%"))
                                 .or(asset_table[:serial_number].matches("%#{@search_text}%"))
                                 .or(asset_table[:license_plate].matches("%#{@search_text}%")))
    end

    set_var_and_yield_if_present :vehicle_type do
      type_id = FtaSupportVehicleType.find_by(name: @vehicle_type) ||
                FtaVehicleType.find_by(name: @vehicle_type)

      asset_table = Asset.arel_table
      @orphaned_assets = @orphaned_assets
                         .where(asset_table[:fta_support_vehicle_type_id].eq(type_id)
                                 .or(asset_table[:fta_vehicle_type_id].eq(type_id)))
    end
    
    respond_to do |format|
      format.html
      format.json {

        # merge fields
        orphaned_assets_json = @orphaned_assets.order("#{params[:sort]} #{params[:order]}").limit(params[:limit]).offset(params[:offset]).collect{ |p|
          p.as_json.merge!({
             serial_number: p.serial_number,
             license_plane: p.license_plate,
             manufacturer_model: p.manufacturer_model,
             service_status_type: p.service_status_type.try(:to_s),
             vehicle_type: (FtaSupportVehicleType.find_by(id: p.fta_support_vehicle_type_id) || FtaVehicleType.find_by(id: p.fta_vehicle_type_id)).to_s,
             action: new_asset_asset_fleets_path(asset_object_key: p.object_key, format: :js)
         })
        }

        render :json => {
            :total => @orphaned_assets.count,
            :rows =>  orphaned_assets_json
        }
      }
      format.xls
    end
  end

  # GET /asset_fleets/1
  def show
    @category = FtaAssetCategory.asset_types(AssetType.where(class_name:@asset_fleet.asset_fleet_type.class_name)).first
    add_breadcrumb (@category.name == "Equipment") ? "Support Vehicles" : @category.to_s,
                   asset_fleets_path(fta_asset_category_id: @category) if @category
    
    add_breadcrumb @asset_fleet

    builder = AssetFleetBuilder.new(@asset_fleet.asset_fleet_type, @asset_fleet.organization)
    @available_assets = builder.available_assets(builder.asset_group_values({fleet: @asset_fleet}))

  end

  # GET /asset_fleets/new
  def new
    add_breadcrumb 'New'

    @asset_fleet = AssetFleet.new
  end

  # GET /asset_fleets/1/edit
  def edit
    @category = FtaAssetCategory.asset_types(AssetType.where(class_name:@asset_fleet.asset_fleet_type.class_name)).first

app/views/asset_fleets/_actions.html.haml
- if (can? :update, @asset_fleet)
  .btn-group.pull-right.panel-action
    %button.btn.btn-primary.btn-sm.dropdown-toggle{:data => {:toggle => 'dropdown'}}
      %i.fa.fa-cog
      = " Actions"
      %span.caret
    %ul.dropdown-menu{:role => 'menu'}
      %li
        = link_to edit_asset_fleet_path(@asset_fleet) do
          %i.fa.fa-edit.fa-fw
          = " Update this fleet"
      - if can? :destroy, @asset_fleet
        %li.divider
        %li
          = link_to asset_fleet_path(@asset_fleet), :method => :delete, :data => {:confirm => "Are you sure? The action cannot be undone."}  do
            %i.fa.fa-trash-o.fa-fw
            = " Remove this fleet"

app/views/asset_fleets/_asset_group_values.html.haml
- data = @asset_fleet.formatted_group_by_fields
- data[:labels].zip(data[:data],data[:formats]).each do |row|
  - # FTA related fields are on fleet info tab so ignore
  - unless row[0] == 'Dedicated' || (row[0].include? 'FTA')
    = format_field(row[0], format_using_format(row[1], row[2]))

%br
= format_field('Useful Life Benchmark', @asset_fleet.useful_life_benchmark)
= format_field('Useful Life Remaining', @asset_fleet.useful_life_remaining)

app/views/asset_fleets/_builder.html.haml
:ruby
  table_dom_id = SecureRandom.hex

:css
  .th-inner {
    white-space: normal !important;
  }

#table_actions.btn-toolbar
  = render partial: 'asset_fleets/orphaned_filter'

%fieldset
  %legend Orphaned Assets
  .table-responsive
    %table.table.table-condensed.table-hover{:id => 'asset_server_table',
      :data => {:toggle => 'table',
      :url => orphaned_assets_asset_fleets_path(:asset_type_id => @asset_type_id,
                                             :search_text => @search_text,
                                             :manufacturer_id => @manufacturer_id,
                                             :manufacturer_model => @manufacturer_model,
                                             :manufacture_year => @manufacture_year,
                                             :asset_subtype_id => @asset_subtype_id,
                                             :vehicle_type => @vehicle_type,
                                             :service_status_type_id => @service_status_type_id,
                                             :format => :json),
      :card_view => "false",
      :pagination => 'true',
      :sort_order => 'asc',
      :sortable => 'true',
      :side_pagination => 'server',
      :show_pagination_switch => 'false',
      :page_number => '1',
      :page_list => "[5, 10, 20, 50, 100, 200, 10000]",
      :page_size => current_user.num_table_rows,
      :search => 'false',
      :show_columns => 'true',
      :toolbar => "#table_actions",
      :show_export => 'true',
      :row_style => 'row_style',
      :click_to_select => 'true',
      :show_export => 'true',
      :id_field => 'object_key',
      :export_types => "['csv', 'txt', 'excel']",
      :cookie => 'true',
      :cookie_id_table => "orphanedassetsid",
      :cookie_expire => "1y",
      :maintain_selected => 'true',
      :single_select => 'false'}}



      %thead
        %tr
          %th.left{:data => {:field => 'object_key', :visible => 'false'}} Object Key
          - if @organization_list.count > 1
            %th.left{:data => {:field => 'organization_id',:sortable => 'true'}} Agency

          %th.left{:data => {:field => 'asset_type_id',:sortable => 'true'}} Asset Type
          %th.left{:data => {:field => 'asset_tag', :sortable => 'true'}} Asset Tag
          %th.left{:data => {:field => 'external_id', :sortable => 'true'}} External ID
          %th.left{:data => {:field => 'serial_number', :sortable => 'true'}} VIN
          %th.left{:data => {:field => 'license_plate', :sortable => 'true'}} License Plate
          %th.left{:data => {:field => 'manufacturer_id', :sortable => 'true'}} Manufacturer
          %th.left{:data => {:field => 'manufacturer_model', :sortable => 'true'}} Model
          %th.left{:data => {:field => 'manufacture_year', :sortable => 'true'}} Year Manufactured

          %th.left{:data => {:field => 'asset_subtype_id',:sortable => 'true'}} Asset Subtype
          %th.left{:data => {:field => 'vehicle_type', :sortable => 'true'}} FTA Vehicle Type
          %th.left{:data => {:field => 'service_status_type', :sortable => 'true'}} Status

          %th.left{:data => {:field => 'action', :formatter => 'action_formatter'}} Action


%fieldset
  %legend Asset Fleet Builder

#processing{style: 'display:none;'}
  = render :partial => 'shared/running_process', :locals => {:message => @message}

.row#form
  .col-md-6.col-md-offset-3
    .row
      .col-md-12
        .alert.alert-info
          = render 'builder_notes'
          .row
            - @fta_asset_categories.each do |asset_category|
              .col-sm-12.text-center{style: 'padding-top: 25px;'}
                = link_to runner_asset_fleets_path(fta_asset_category_id: asset_category[:id]), :class => "btn btn-primary btn-sm", :onclick => "$('#processing').show();" do
                  = "Build #{asset_category[:label]} Fleets"

:javascript

  $(document).ready(function() {
    $('#' + '#{table_dom_id}').bootstrapTable('resetWidth');
  });

  $(window).resize(function() {
    $('#' + '#{table_dom_id}').bootstrapTable('resetView');
  });

  function action_formatter(value, data) {
    return '<a class="btn btn-primary btn-sm" title="Add to Fleet" data-remote="true" href="'+value+'"><i class="fa fa-plus"></i> Add to Fleet</a>';
  }

  function boolean_formatter(value) {
    if (parseInt(value)) {
      // hidden div for exporting
      return '<i class="fa fa-check"></i><div style = "visibility: hidden;">Yes</div>';
    } else {
      return '<div style = "visibility: hidden;">No</div>';
    }
  };

app/views/asset_fleets/_builder_notes.html.haml
.text-center
  %p
    The <strong>Asset Fleet Builder</strong> analyzes your organization's inventory and groups assets into fleets following parameters set by NTD reporting. If you run the asset fleet builder, you will delete all existing fleets and regroup the assets from scratch. Please note that you will lose any existing fleet data.
  %p
    Once the builder has completed, you will receive a notification. Please review your fleets at that time and add fleet specific information.

app/views/asset_fleets/_index_actions.html.haml
.row
  .col-md-12
    - if can? :create, AssetFleet
      .btn-group{style: 'margin-left: 10px; margin-bottom: 20px;'}
        = link_to builder_asset_fleets_path, :class => 'btn btn-default' do
          %i.fa.fa-cogs.fa-fw
          = "Fleet Builder"
        = link_to new_asset_fleet_path, :class => 'btn btn-default' do
          %i.fa.fa-plus.fa-fw
          = "Add Asset Fleet"

app/views/asset_fleets/_index_filter.html.haml
= form_tag asset_fleets_path, :id => 'filter_form', :method => "get", :class => 'navbar-form navbar-right panel-action', style: 'padding-top: 1px' do
  .form-group
    = hidden_field_tag(:fta_asset_category_id, @fta_asset_category.id)
    = select_tag(:primary_fta_mode_type_id, options_from_collection_for_select(@primary_modes, "id", "to_s",  @primary_fta_mode_type_id), :class => "form-control", :style => "width: 150px;", :prompt => "Any Mode...")
    - if @service_types
      = select_tag(:primary_fta_service_type_id, options_from_collection_for_select(@service_types, "id", "to_s",  @primary_fta_service_type_id), :class => "form-control", :style => "width: 150px;", :prompt => "Any Service Type...")

    = text_field_tag(:text_search, @text_search, class: 'form-control', placeholder: @text_search_prompt)
    
    = select_tag(:fta_vehicle_type_id, options_from_collection_for_select(@vehicle_types, "id", "to_s",  @fta_vehicle_type_id), :class => "form-control", :style => "width: 150px;", :prompt => "Any Vehicle Type...")

    - if @manufacturers
      = select_tag(:manufacturer_id, options_from_collection_for_select(@manufacturers, "id", "to_s",  @manufacturer_id), :class => "form-control", :style => "width: 150px;", :prompt => "Any Manufacturer...")
    
    = number_field_tag(:manufacture_year, @manufacture_year, class: 'form-control', :style => "width: 160px;", placeholder: 'Year Manufactured', min: 1950, max: 2100)

    = select_tag(:status, options_for_select(['Active', 'Retired'], @status), :class => "form-control", :style => "width: 150px;")

    = button_tag :class => 'btn btn-default', :type => 'submit' do
      %i.fa.fa-filter
      
    = link_to asset_fleets_path(fta_asset_category_id: @fta_asset_category), :class => 'btn btn-default btn-xs' do
      %span.fa-stack
        %i.fa.fa-filter.fa-stack-1x
        %i.fa.fa-ban.fa-stack-2x

:javascript
  $("input[placeholder]").each(function () {
    $(this).attr('size', $(this).attr('placeholder').length);
  });

  $('#filter_form').validate({
  });

  $(function() {
    $('#manufacturer_year').keypress(function (e) {
      console.log(e.which);
      if (e.which == 46) { // .
        e.preventDefault();
      }
    });
  });

app/views/asset_fleets/_revenue_vehicles_asset_fleet.html.haml
= format_field('Vehicle Type', @asset_fleet.asset_fleet_type.class_name == 'SupportVehicle' ? @asset_fleet.get_fta_support_vehicle_type : @asset_fleet.get_fta_vehicle_type)
= format_field('Primary Mode', @asset_fleet.get_primary_fta_mode_type)
= format_field('Type of Service', @asset_fleet.get_primary_fta_service_type)
%br
= format_field('Total Vehicles', format_as_integer(@asset_fleet.total_count))
= format_field('Active Vehicles', format_as_integer(@asset_fleet.active_count))
= format_field('ADA Accessible Vehicles', format_as_integer(@asset_fleet.ada_accessible_count))
= format_field('Emergency Contingency Vehicles', format_as_integer(@asset_fleet.fta_emergency_contingency_count))
%br
= format_field('Secondary Mode', @asset_fleet.get_secondary_fta_mode_type)
= format_field('Secondary Type of Service', @asset_fleet.get_secondary_fta_service_type)
%br
= format_field('Dedicated Fleet', format_as_yes_no(@asset_fleet.get_dedicated))
= format_field('Ownership Type', @asset_fleet.get_fta_ownership_type)
= format_field('Funding Type', @asset_fleet.get_fta_funding_type)
%br
= format_field("Active", format_as_boolean(@asset_fleet.active))
%br
= format_field('Notes', format_as_text(@asset_fleet.notes))

app/views/asset_fleets/_revenue_vehicles_index_table.html.haml
:ruby
  table_dom_id = SecureRandom.hex
  
:css
  .th-inner {
    white-space: normal !important;
  }

#table_actions.btn-toolbar
  = render partial: 'asset_fleets/index_filter'
  
.table-responsive
  %table.table.table-condensed.table-hover{:id => table_dom_id,
    :data => {:toggle => 'table',
    :url => asset_fleets_path(:fta_asset_category_id => @fta_asset_category.id,
                              :primary_fta_mode_type_id => @primary_fta_mode_type_id,
                              :primary_fta_service_type_id => @primary_fta_service_type_id,
                              :search_text => @search_text,
                              :fta_vehicle_type_id => @fta_vehicle_type_id,
                              :manufacturer_id => @manufacturer_id,
                              :manufacture_year => @manufacture_year,
                              :status => @status,
                              :format => :json),
    :card_view => "false",
    :pagination => 'true',
    :sort_order => 'asc',
    :sortable => 'true',
    :side_pagination => 'server',
    :show_pagination_switch => 'false',
    :page_number => '1',
    :page_list => "[5, 10, 20, 50, 100, 200, 10000]",
    :page_size => current_user.num_table_rows,
    :search => 'false',
    :toolbar => "#table_actions",
    :show_columns => 'false',
    :show_export => 'true',
    :row_style => 'row_style',
    :click_to_select => 'false',
    :show_export => 'true',
    :export_types => "['csv', 'txt', 'excel']",
    :cookie => 'true',
    :cookie_id_table => "asset_fleetsid",
    :cookie_expire => "1y",
    :maintain_selected => 'false',
    :single_select => 'false'}}

    %thead
      %tr
        %th.left{:data => {:field => 'object_key', :visible => 'false'}} Object Key
        - if @organization_list.count > 1
          %th.left{:data => {:field => 'organization',:sortable => 'true'}} Agency
        %th.left{:data => {:field => 'ntd_id', :sortable => 'true'}} RVI ID
        %th.left{:data => {:field => 'agency_fleet_id', :sortable => 'true'}} Agency Fleet ID
        %th.left{:data => {:field => 'primary_fta_mode_type_id', :sortable => 'true'}} Primary Mode
        %th.left{:data => {:field => 'primary_fta_service_type_id', :sortable => 'true'}} Type of Service
        %th.right{:data => {:field => 'total_count', :sortable => 'false'}} Total Vehicles
        %th.right{:data => {:field => 'active_count', :sortable => 'false'}} Active Vehicles
        %th.left{:data => {:field => 'fta_vehicle_type_id', :sortable => 'true'}} FTA Vehicle Type

        %th.left{:data => {:field => 'manufacturer_id', :sortable => 'true'}} Manufacturer
        %th.left{:data => {:field => 'manufacturer_model', :sortable => 'true'}} Model
        %th.left{:data => {:field => 'manufacture_year', :sortable => 'true'}} Year Manufactured

        %th.right{:data => {:field => 'useful_life_benchmark', :sortable => 'false'}} Useful Life Benchmark
        %th.right{:data => {:field => 'useful_life_remaining', :sortable => 'false'}} Useful Life Remaining
        %th.center{:data => {:field => 'action', :formatter => 'action_formatter'}} Action

:javascript
  $(document).ready(function() {
    $('##{table_dom_id}').bootstrapTable('resetWidth');

    $('##{table_dom_id}').on('post-body.bs.table', function (e) {
    $("td").filter(function() { return $(this).text() === '-'}).removeClass('left').removeClass('right').addClass('center');
    });
  });

  $(window).resize(function() {
    $('##{table_dom_id}').bootstrapTable('resetView');
  });

  // var org_filter = #{@org_filter || []};
  // var fiscal_year_filter = #{@fiscal_year_filter || []};
  // var capital_project_flag_filter = #{@capital_project_flag_filter || []};
  // var capital_project_type_filter = #{@capital_project_type_filter || []};
  // var asset_subtype_filter = #{@asset_subtype_filter || []};

  // function query_params(params) {
  //   if(org_filter.length > 0) {
  //     params.org_filter = org_filter;
  //   }
  //
  //   if(fiscal_year_filter.length > 0) {
  //     params.fiscal_year_filter = fiscal_year_filter;
  //   }
  //
  //   if(capital_project_flag_filter.length > 0) {
  //     params.capital_project_flag_filter = capital_project_flag_filter;
  //   }
  //
  //   if(capital_project_type_filter.length > 0) {
  //     params.capital_project_type_filter = capital_project_type_filter;
  //   }
  //
  //   if(asset_subtype_filter.length > 0) {
  //     params.asset_subtype_filter = asset_subtype_filter;
  //   }
  //
  //   return params;
  // }

  var formatMoney = function(n, c, d, t) {
    var c = isNaN(c = Math.abs(c)) ? 0 : c,
    d = d == undefined ? "." : d,
    t = t == undefined ? "," : t,
    s = n < 0 ? "-" : "",
    i = parseInt(n = Math.abs(+n || 0).toFixed(c)) + "",
    j = (j = i.length) > 3 ? j % 3 : 0;
    return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
  }

  function boolean_formatter(value) {
    if (value) {
      // add hidden div for exporting
      return '<i class="fa fa-check"></i><div style = "visibility: hidden;">Yes</div>';
    } else {
      return '<div style = "visibility: hidden;">No</div>';
    }
  }

  function currency_formatter(value) {
    return "$" + formatMoney(value);
  }

  function action_formatter(value, data) {
    return "<a class='btn btn-primary btn-sm' href='#{asset_fleets_path}/"+data.object_key+"'>View</a>";
  }

app/views/asset_fleets/_update_asset_mileage.html.haml
- @asset_fleet = @asset_event.asset.asset_fleets.first
= render 'asset_fleets/asset_mileages_datatable'

app/views/asset_fleets/builder.html.haml
= render partial: "builder"

app/views/asset_fleets/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %fieldset
      %legend Update Asset Fleet
      = render(:partial => 'shared/form_errors', :locals => {:obj => @asset_fleet}) unless @asset_fleet.errors.empty?

      = render 'form'