config/routes.rb
Rails.application.routes.draw do

  resources :asset_fleets do
    collection do
      get 'orphaned_assets'

      get 'new_asset'
      get 'add_asset'
      get 'new_fleet'

      get 'builder'
      get 'runner'
    end

    member do
      delete 'remove_asset'
    end

  end

  # NTD Forms Controllers
  resources :forms, :only => [] do
    resources :ntd_forms do

      # Build controller for form wizard
      resources :steps, controller: 'ntd_forms/steps'

      collection do
        get   'download_file'
      end

      member do
        get 'fire_workflow_event'
        get 'generate'
      end

      resources :comments

    end
  end
  
end

app/controllers/ntd_forms/steps_controller.rb
class NtdForms::StepsController < FormAwareController

  include Wicked::Wizard

  before_action :get_form, :only => [:show, :update]

  # Set the breadcrumbs
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Forms", :forms_path

  steps :agency_information
        #:admin_and_maint_facility_inventory,
        #:passenger_and_parking_facility_inventory,
        #:service_vehicle_inventory,
        #:revenue_vehicle_inventory,

  def show

    add_breadcrumb @form_type.name, form_path(@form_type)
    add_breadcrumb step.to_s.titleize

    # get data for the current form
    # builds the appropritae association / sub-form
    # TODO: use service to query assets and their associated tables
    # where NtdService.get_data runs its queries and returns an array of hashes
    case step
      when :agency_information
        @form.reporter_name = current_user.name
        @form.reporter_title = current_user.title
        @form.reporter_department = nil
        @form.reporter_email = current_user.email
        @form.reporter_phone = current_user.phone
        @form.reporter_phone_ext = current_user.phone_ext

      when :admin_and_maint_facility_inventory
        # @form.ntd_admin_and_maintenance_facilities.build(NtdReportingService.get_data(step))
      when :passenger_and_parking_facility_inventory
        # @form.ntd_passenger_and_parking_facilities.build(NtdReportingService.get_data(step))
      when :service_vehicle_inventory
        # @form.ntd_service_vehicle_fleets.build(NtdReportingService.get_data(step))
      when :revenue_vehicle_inventory
        #@form.ntd_revenue_vehicle_fleets.build(NtdReportingService.revenue_vehicle_fleets(user.organizations))
    end

    @has_prev_step = previous_step

    render_wizard

  end

  def update

    add_breadcrumb @form_type.name, form_path(@form_type)
    add_breadcrumb "New"


    case step
      when :agency_information

        reporting_service = NtdReportingService.new(form: @form)

        @form.ntd_revenue_vehicle_fleets = reporting_service.revenue_vehicle_fleets(Organization.where(id: @form.organization_id))
        @form.ntd_service_vehicle_fleets = reporting_service.service_vehicle_fleets(Organization.where(id: @form.organization_id))
        #@form.ntd_passenger_and_parking_facilities = reporting_service.passenger_and_parking_facilities(Organization.where(id: @form.organization_id))
        @form.ntd_admin_and_maintenance_facilities = reporting_service.admin_and_maintenance_facilities(Organization.where(id: @form.organization_id))

        @form.update_attributes(form_params.merge({processing_log: reporting_service.process_log}))

      when :admin_and_maint_facility_inventory
        # @form.ntd_admin_and_maintenance_facilities.create(NtdReportingService.get_data(step))
      when :passenger_and_parking_facility_inventory
        # @form.ntd_passenger_and_parking_facilities.create(NtdReportingService.get_data(step))
      when :service_vehicle_inventory
        # @form.ntd_service_vehicle_fleets.create(NtdReportingService.get_data(step))
      when :revenue_vehicle_inventory
        # @form.ntd_revenue_vehicle_fleets.create(NtdReportingService.get_data(step))
    end

    render_wizard @form
  end

  private

  def get_form
    @form = NtdForm.find_by(:object_key => params[:ntd_form_id])
  end

  def form_params
    params.require(:ntd_form).permit(NtdForm.allowable_params)
  end

  def finish_wizard_path
    get_form
    return form_ntd_form_url(@form_type, @form)
  end

end

app/controllers/ntd_forms_controller.rb
class NtdFormsController < FormAwareController

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Forms", :forms_path

  # Include the fiscal year mixin
  include FiscalYear

  before_action :get_form,  :except =>  [:index, :create, :new, :download_file]

  INDEX_KEY_LIST_VAR          = "ntd_forms_key_list_cache_var"

  def index

    add_breadcrumb @form_type.name, form_path(@form_type)
    @fiscal_years = get_fiscal_years

     # Start to set up the query
    conditions  = []
    values      = []

    # Check to see if we got an organization to sub select on.
    @org_filter = params[:org_id]
    conditions << 'organization_id IN (?)'
    if @org_filter.blank?
      values << @organization_list
    else
      @org_filter = @org_filter.to_i
      values << [@org_filter]
    end

    # See if we got search
    @fiscal_year = params[:fiscal_year]
    unless @fiscal_year.blank?
      @fiscal_year = @fiscal_year.to_i
      conditions << 'fy_year = ?'
      values << @fiscal_year
    end

    @forms = NtdForm.where(conditions.join(' AND '), *values).order(:fy_year)

    unless params[:format] == 'xls'
      # cache the set of object keys in case we need them later
      cache_list(@forms, INDEX_KEY_LIST_VAR)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @forms }
      format.xls
    end
  end

  def show

    add_breadcrumb @form_type.name, form_path(@form_type)
    add_breadcrumb @form

    # get the @prev_record_path and @next_record_path view vars
    get_next_and_prev_object_keys(@form, INDEX_KEY_LIST_VAR)
    @prev_record_path = @prev_record_key.nil? ? "#" :  form_ntd_form_path(@form_type, @prev_record_key)
    @next_record_path = @next_record_key.nil? ? "#" : form_ntd_form_path(@form_type, @next_record_key)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @form }
    end
  end


  def new

    add_breadcrumb "New"

    @form = NtdForm.new

    @fiscal_years = get_fiscal_years

  end

  def create

    params[:ntd_form][:start_date] = reformat_date(params[:ntd_form][:start_date]) unless params[:ntd_form][:start_date].blank?
    params[:ntd_form][:end_date] = reformat_date(params[:ntd_form][:end_date]) unless params[:ntd_form][:end_date].blank?

    @form = NtdForm.new(form_params)
    @form.form = @form_type

    if @form.save
      redirect_to form_ntd_form_steps_url @form_type, @form
    else
      render :new
    end
  end

  def edit

    redirect_to form_ntd_form_steps_url @form_type, @form

  end

  def destroy

    @form.destroy
    notify_user(:notice, "Form was successfully removed.")
    respond_to do |format|
      format.html { redirect_to form_ntd_forms_url(@form_type) }
      format.json { head :no_content }
    end
  end

  def generate

    add_breadcrumb @form_type.name, form_path(@form_type)
    add_breadcrumb @form, form_ntd_form_path(@form_type, @form)
    add_breadcrumb 'Generate', generate_form_ntd_form_path(@form_type, @form)

    # Find out which builder is used to construct the template and create an instance
    builder = DirEntInvTemplateBuilder.new(:ntd_form => @form, :organization_list => [@form.organization_id])

    # Generate the spreadsheet. This returns a StringIO that has been rewound
    stream = builder.build

    # Save the template to a temporary file and render a success/download view
    file = Tempfile.new ['template', '.tmp'], "#{Rails.root}/tmp"
    ObjectSpace.undefine_finalizer(file)
    #You can uncomment this line when debugging locally to prevent Tempfile from disappearing before download.
    @filepath = file.path
    @filename = "#{@form.organization.short_name}_DirEntInv_#{Date.today}.xlsx"
    begin
      file << stream.string
    rescue => ex
      Rails.logger.warn ex
    ensure
      file.close
    end
    # Ensure you're cleaning up appropriately...something wonky happened with
    # Tempfiles not disappearing during testing
    respond_to do |format|
      format.js
      format.html
    end
  end

  def download_file
    # Send it to the user
    filename = params[:filename]
    filepath = params[:filepath]
    data = File.read(filepath)
    send_data data, :filename => filename, :type => "application/vnd.ms-excel"
  end

  protected


  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def form_params
    params.require(:ntd_form).permit(NtdForm.allowable_params)
  end

  def reformat_date(date_str)
    form_date = Date.strptime(date_str, '%m/%d/%Y')
    return form_date.strftime('%Y-%m-%d')
  end

  def get_form
    # See if it is our project
    @form = NtdForm.find_by(:object_key => params[:id]) unless params[:id].nil?
    # if not found or the object does not belong to the users
    # send them back to index.html.erb
    if @form.nil?
      notify_user(:alert, 'Record not found!')
      redirect_to(form_ntd_forms_url(@form_type))
      return
    end
  end

end

app/views/ntd_forms/_actions.html.haml
- if can? :update, @form
  .btn-group.pull-right.panel-action
    %button.btn.btn-primary.btn-sm.dropdown-toggle{:data => {:toggle => 'dropdown'}}
      %i.fa.fa-cog
      = " Actions"
      %span.caret
    %ul.dropdown-menu{:role => 'menu'}
      %li
        - @form.allowable_events.each do |evt|
          = link_to fire_workflow_event_form_ntd_form_path(@form_type, @form, :event => evt) do
            %i.fa.fa-fw{:class => get_event_icon(evt)}
            = "#{evt} this form"
      %li.divider
      %li
        = link_to generate_form_ntd_form_path(@form_type, @form) do
          %i.fa.fa-download.fa-fw
          = " Download A-80"
      %li.divider
      %li
        = link_to edit_form_ntd_form_path(@form_type, @form) do
          %i.fa.fa-edit.fa-fw
          = " Update this form"
      %li.divider
      %li
        = link_to form_ntd_form_path(@form_type, @form), :method => :delete, :data => {:confirm => "Are you sure you want to remove this form? The action can't be undone."} do
          %i.fa.fa-trash-o.fa-fw
          = " Remove this form"

app/views/ntd_forms/_comments.html.haml
.row
  .col-md-12{:style => 'height:200px;overflow-y:auto;'}
    - if @form.comments.empty?
      %p There are no comments for this NTD report.
    - else
      = render :partial => 'shared/comments', :locals => {:comments => @form.comments}

- if can? :create, @form.comments.build
  .row
    .col-md-12
      %fieldset
        %legend Add Comment
        = form_for [@form, Comment.new], :html => {:multipart => true, :class => 'form-vertical comment_form' }, :url => funding_source_comments_path(@form, Comment.new), :role => 'form' do |f|
          .form-group
            = f.text_area :comment, :class => 'form-control', :placeholder => 'Enter a new comment...', :required => true, :minlength => 10, :maxlength => 254
          = f.submit :class => 'btn btn-primary', :id => 'comment_submit'

:javascript

  // jquery validations
  $('.comment_form').validate({
    ignore: [], //validate hidden fields
    submitHandler: function(form) {
      form.submit();
    }
  });

app/views/ntd_forms/_form.html.haml
= simple_form_for([@form_type, @form],
  :html => {:class => 'form-vertical ntd_form_form' },
  :wrapper => :vertical_form,
  :wrapper_mappings => {:check_boxes => :vertical_radio_and_checkboxes, :radio_buttons => :vertical_radio_and_checkboxes, :file => :vertical_file_input, :boolean => :vertical_boolean}) do |f|

  = f.association :organization, :collection => Organization.where(id: @organization_list), :label_method => :coded_name
  = f.input :fy_year, as: :fiscal_year, :label => 'Fiscal Year'

  = f.button :submit, 'Save NTD Form', :class => "btn btn-primary"

:javascript
  $(document).ready(function(){
    transam.make_same_height('.header-part');
  });

  transam.make_fiscal_year('input.fiscal_year');

  // jquery validations
  $('.ntd_form_form').validate({
    submitHandler: function(form) {
      form.submit();
    }
  });

app/views/ntd_forms/_index_actions.html.haml
.row
  .col-md-12
    - if can? :create, NtdForm
      .btn-group{style: 'margin-left: 10px;'}
        = link_to new_form_ntd_form_path(@form_type), :class => 'btn btn-default' do
          %i.fa.fa-plus.fa-fw
          = " New NTD Report"

app/views/ntd_forms/_index_table.html.haml
:ruby
  table_dom_id = SecureRandom.hex

#forms_datatable_actions.btn-toolbar
  = render :partial => "ntd_forms/index_actions"

.table-responsive
  %table.table.table-condensed.table-hover{:id => table_dom_id,
    :data => {:toggle => 'table',
    :card_view => "false",
    :pagination => 'true',
    :sort_order => 'asc',
    :sortable => 'true',
    :side_pagination => 'server',
    :show_pagination_switch => 'false',
    :page_number => '1',
    :page_list => "[5, 10, 20, 50, 100, 200, 10000]",
    :page_size => current_user.num_table_rows,
    :search => 'false',
    :show_columns => 'true',
    :toolbar => "#forms_datatable_actions",
    :show_export => 'true',
    :row_style => 'row_style',
    :click_to_select => 'true',
    :show_export => 'true',
    :export_types => "['csv', 'txt', 'excel']",
    :cookie => 'true',
    :cookie_id_table => "ntd_reportsid",
    :cookie_expire => "1y",
    :maintain_selected => 'true',
    :single_select => 'false'}}

    %thead
      %tr
        %th.left Organization
        %th.right Fiscal Year
        %th.right Status

    %tbody
      - forms.each do |f|
        %tr{:data => {:action_path => form_ntd_form_path(@form_type, f)}}
          %td.left= f.organization
          %td.right= format_as_fiscal_year(f.fy_year)
          %td.right= f.state.humanize

app/views/ntd_forms/_process_log.html.haml
.row
  .col-md-12
    = @form.processing_log.html_safe unless @form.processing_log.blank?

app/views/ntd_forms/_report.html.haml
%p Report for this form

app/views/ntd_forms/_scripts.html.haml
:javascript
  
  var user_tab_key = 'ntd_form_tab_key';
  
  $(document).ready(function() {

    transam.make_same_height('.header-part');

    // Manage the tabs
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
      // save the latest tab
      var this_tab = $(this).attr('href');
      transam.set_ui_key_value(user_tab_key, this_tab);


      transam.make_same_height('.header-part');
    });
  });
  $(function() {
    var last_tab = transam.get_ui_key_value(user_tab_key);
    if (last_tab) {
      $('a[href="'+last_tab+'"]').tab('show');
    } else {
      // Default to the first tab if no tab is stored
      $('a[data-toggle="tab"]:first').tab('show');
    }   
  }); 

app/views/ntd_forms/_summary.html.haml
= format_field("Organization", form.organization )
= format_field("Year", format_as_fiscal_year(form.fy_year) )
= format_field("Status", format_as_label(form.state) )
= format_field("Last Updated", format_as_date_time(form.updated_at))
%hr
= format_field("Reporter Name", form.reporter_name)
= format_field("Reporter Title", form.reporter_title)
= format_field("Reporter Department", form.reporter_department)
= format_field("Reporter Email", form.reporter_email)
= format_field("Reporter Phone", format_as_phone_number(form.reporter_phone) )
= format_field("Ext.", form.reporter_phone_ext) unless form.reporter_phone_ext.blank?

app/views/ntd_forms/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %fieldset
      %legend Update NTD Form
      = render(:partial => 'shared/form_errors', :locals => {:obj => @form}) unless @form.errors.empty?

      = render 'form'

= render 'scripts'

app/views/ntd_forms/generate.html.haml
.row
  .col-xs-12.text-center{:style => 'min-height: 300px;padding:20px;'}
    %i.fa.fa-thumbs-up.fa-4x
    %h4
      Success
    %p
      Click the button below to download the file to your computer.
    %p
      = link_to download_file_form_ntd_forms_path(@form_type, :filename => @filename, :filepath => @filepath), :class => "btn btn-primary btn-lg" do
        %i.fa.fa-download
        Download File

app/views/ntd_forms/index.html.haml
%ul.nav.nav-tabs
  %li.active
    %a{:href => "#fleets", :data =>{:toggle => 'tab'}}
      Fleet Manager
  %li
    %a{:href => "#ntd", :data =>{:toggle => 'tab'}}
      NTD Reports

.tab-content
  .tab-pane.fade.in.active#fleets

    = render :partial => 'asset_fleets/index_actions'

    %ul.nav.nav-tabs
      - AssetFleetType.all.each_with_index do |fleet_type, idx|
        - asset_type = AssetType.find_by(class_name: fleet_type.class_name)
        %li{idx == 0 ? {class: 'active'} : {}}
          %a{:href => "##{fleet_type.class_name.underscore}", :data =>{:toggle => 'tab'}}
            %i{:class => "#{asset_type.display_icon_name} fa-fw"}
            = asset_type

    .tab-content
      - AssetFleetType.all.each_with_index do |fleet_type, idx|
        .tab-pane.fade{idx == 0 ? {id: fleet_type.class_name.underscore, class: 'in active'} : {id: fleet_type.class_name.underscore}}
          - view_component = "#{fleet_type.class_name.underscore}_index_table"
          - if lookup_context.template_exists?(view_component, 'asset_fleets', true)
            = render :partial => "asset_fleets/#{view_component}"

  .tab-pane.fade#ntd
    .col-sm-12.col-md-10.col-md-offset-1
      .row
        .col-md-12
          = render :partial => 'index_table', :locals => {:forms => @forms}

app/views/ntd_forms/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %fieldset
      %legend New NTD Report
      = render(:partial => 'shared/form_errors', :locals => {:obj => @form}) unless @form.errors.empty?

      = render 'form'

= render 'scripts'

app/views/ntd_forms/show.html.haml
.row
  .col-md-3
    .panel.panel-default.header-part
      .panel-heading
        .row
          .col-md-6
            %h3.panel-title
              %i.fa.fa-list
              = @form
          .col-md-6
            = render 'actions'
      .panel-body
        = render :partial => 'summary', :locals => {:form => @form}

  .col-md-9
    .panel.panel-default.header-part
      .panel-heading
        .row
          .col-md-12
            %h3.panel-title
              %i.fa.fa-folder-open
              Details

      .panel-body
        = render 'details'

= render 'scripts'