config/routes.rb
Rails.application.routes.draw do

  resources :asset_fleets do
    collection do
      get 'orphaned_assets'

      get 'new_asset'
      get 'add_asset'
      get 'new_fleet'

      get 'builder'
      get 'runner'
    end

    member do
      delete 'remove_asset'
    end

  end

  # NTD Forms Controllers
  resources :forms, :only => [] do
    resources :ntd_forms do

      # Build controller for form wizard
      resources :steps, controller: 'ntd_forms/steps'

      collection do
        get   'download_file'
      end

      member do
        get 'fire_workflow_event'
        get 'generate'
      end

      resources :comments

    end
  end
  
end

app/views/layouts/asset_fleets.html.haml
- content_for :content do

  .indent
  .col-sm-12
    %h2 Fleets
    %hr
    - unless ['show', 'edit'].include? params[:action]
      %ul.nav.nav-pills
        - rev_vehicles = FtaAssetCategory.find_by(name: 'Revenue Vehicles')
        - support_vehicles = FtaAssetCategory.find_by(name: 'Equipment')
        %li{@fta_asset_category == rev_vehicles ? {class: 'active'}: {}}
          = link_to asset_fleets_path(fta_asset_category_id: rev_vehicles.id), :class => 'btn btn-default' do
            = rev_vehicles
        %li{@fta_asset_category == support_vehicles ? {class: 'active'}: {}}
          = link_to asset_fleets_path(fta_asset_category_id: support_vehicles.id), :class => 'btn btn-default' do
            Support Vehicles
        %li{params[:action] == 'builder' ? {class: 'active'}: {}}
          = link_to builder_asset_fleets_path, :class => 'btn btn-default' do
            Manage Fleets

    .modal.fade#form-modal{:tabindex => -1, :role => 'dialog', :aria => {:hidden => true}}

    .row.content-spacer
      = yield

= render template: "layouts/application"